### ISSUE TITLE
Driver broken with webdriverio v9

### ISSUE THREAD

**Issue by regan-karlewicz** [headspinio/appium-roku-driver#175]
Hello! Today when setting this up I noticed that this driver is not compatible with webdriverio v9+

For context, here is the script I am using:

```javascript
const { remote } = require("webdriverio");

const capabilities = {
  platformName: "Roku",
  "appium:automationName": "roku",
  "appium:rokuHost": "...redacted...",
  "appium:rokuEcpPort": 8060,
  "appium:rokuWebPort": 80,
  "appium:rokuUser": "...redacted...",
  "appium:rokuPass": "...redacted..."
};

const wdOpts = {
  hostname: "127.0.0.1",
  port: 4723,
  logLevel: "info",
  capabilities,
};

async function runTest() {
  const driver = await remote(wdOpts);

  try {
    await driver.executeScript("roku: deviceInfo", []);
  } finally {
    await driver.pause(1000);
    await driver.deleteSession();
  }
}

runTest().catch(console.error);
```

When attempting to use this driver with webdriverio v9+, I run into the following error on start of the Appium script:

```
2024-11-25T19:31:54.259Z INFO webdriver: COMMAND getContext()
2024-11-25T19:31:54.260Z INFO webdriver: [GET] http://127.0.0.1:4723/session/7a160a12-320c-4c7c-9491-1d75c0b4eabd/context
2024-11-25T19:31:54.266Z WARN webdriver: WebDriverError: Method has not yet been implemented when running "context" with method "GET"
2024-11-25T19:31:54.267Z INFO webdriver: Retrying 1/3
2024-11-25T19:31:54.267Z INFO webdriver: [GET] http://127.0.0.1:4723/session/7a160a12-320c-4c7c-9491-1d75c0b4eabd/context
2024-11-25T19:31:54.773Z WARN webdriver: WebDriverError: Method has not yet been implemented when running "context" with method "GET"
2024-11-25T19:31:54.774Z INFO webdriver: Retrying 2/3
2024-11-25T19:31:54.774Z INFO webdriver: [GET] http://127.0.0.1:4723/session/7a160a12-320c-4c7c-9491-1d75c0b4eabd/context
2024-11-25T19:31:55.787Z WARN webdriver: WebDriverError: Method has not yet been implemented when running "context" with method "GET"
2024-11-25T19:31:55.788Z INFO webdriver: Retrying 3/3
2024-11-25T19:31:55.788Z INFO webdriver: [GET] http://127.0.0.1:4723/session/7a160a12-320c-4c7c-9491-1d75c0b4eabd/context
2024-11-25T19:31:55.799Z ERROR webdriver: WebDriverError: Method has not yet been implemented when running "context" with method "GET"
```

In the Appium server:

```
[9e29f66f][HTTP] --> GET /session/9e29f66f-3514-4316-845c-5001e8a1f103/context {}
[9e29f66f][RokuDriver@7b11] Calling AppiumDriver.getCurrentContext() with args: ["9e29f66f-3514-4316-845c-5001e8a1f103"]
[9e29f66f][RokuDriver@7b11] Encountered internal error running command: NotYetImplementedError: Method has not yet been implemented
    at RokuDriver.executeCommand (/Users/foo/workspace/playground/appium/node_modules/@appium/base-driver/lib/basedriver/driver.ts:102:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at defaultBehavior (/Users/foo/workspace/playground/appium/node_modules/appium/lib/appium.js:1135:14)
    at AppiumDriver.executeWrappedCommand (/Users/foo/workspace/playground/appium/node_modules/appium/lib/appium.js:1241:16)
    at AppiumDriver.executeCommand (/Users/foo/workspace/playground/appium/node_modules/appium/lib/appium.js:1147:17)
    at asyncHandler (/Users/foo/workspace/playground/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:387:19)
[9e29f66f][HTTP] <-- GET /session/9e29f66f-3514-4316-845c-5001e8a1f103/context 405 1 ms - 868
```

It appears that v9+ will always try to GET on the session context on script start. Downgrading to webdriverio v8.40.5 fixes the problem. 

I'm not sure if this is the right place to report the incompatibility, or if I should open an issue with webdriverio to support configuring this context check. Quickly looking through their configuration docs didn't yield any results. Please let me know if I should open an issue with webdriverio instead.

**Comment by KazuCocoa** [comment]
I guess webdriverio expects only UIA2(or Espresso)/XCUITest drivers in Appium usage. So, they may need to provide a method to bypass the check to support non-mobile devices with Appium ideally. But I guess non-mobiles are their out of scope. We could provide only NATIVE_APP context for all TV related drivers as a workaround for webdriverio.

**Comment by KazuCocoa** [comment]
Or using https://www.npmjs.com/package/webdriver directly is probably a good idea for future maintenance. It is also provided by webdriverio project, but it is a more thin webdriver package for JS.

**Comment by KazuCocoa** [comment]
Perhaps https://github.com/headspinio/appium-roku-driver/pull/176 could work. It always returns the `NATIVE_APP` context value.

**Comment by regan-karlewicz** [comment]
@KazuCocoa Thank you for your work here, really appreciate the quick response, suggestions and action.
