### ISSUE TITLE
Getting a "socket hang up" error message

### ISSUE THREAD

**Issue by semeguze** [headspinio/appium-roku-driver#45]
## The problem

Using this driver with the Appium Inspector tool is throwing a "socket hang up" error message.

## Environment

* Appium version: `2.0.0-beta.48`
* Last Appium version that did not exhibit the issue: N/A
* Desktop OS/version used to run Appium: `MacOS Ventura 13.1 (22C65)`
* Node.js version: `v19.1.0`
* Npm version: `9.2.0`
* Mobile platform/version under test: `40S325 - 8124X - Roku v11.5.0 build 4312-48`
* Real device or emulator/simulator: `TCL TV Roku Device`
* Appium CLI: `Appium Inspector`
* Java version: `11.0.17`
* appium-roku-driver version: `2.0.8`

## Details

I'm trying to inspect my Roku device using the Appium Inspector tool, but I'm getting an error:

```javascript
[Appium] Attempting to find matching driver for automationName 'roku' and platformName 'Roku'
[Appium] The 'roku' driver was installed and matched caps.
[Appium] Will require it at /Users/sebastian.mesa/.appium/node_modules/@headspinio/appium-roku-driver
[debug] [Appium] Requiring driver at /Users/sebastian.mesa/.appium/node_modules/@headspinio/appium-roku-driver
[AppiumDriver@22e0] Appium v2.0.0-beta.48 creating new RokuDriver (v2.0.8) session
[AppiumDriver@22e0] Checking BaseDriver versions for Appium and RokuDriver
[AppiumDriver@22e0] Appium's BaseDriver version is 9.1.0
[AppiumDriver@22e0] RokuDriver's BaseDriver version is 9.1.0
[debug] [RokuDriver@f014] Creating session with W3C capabilities: {
[debug] [RokuDriver@f014]   "alwaysMatch": {
[debug] [RokuDriver@f014]     "platformName": "Roku",
[debug] [RokuDriver@f014]     "appium:automationName": "roku",
[debug] [RokuDriver@f014]     "appium:app": "/Users/sebastian.mesa/Binaries/Redacted.zip",
[debug] [RokuDriver@f014]     "appium:rokuHost": "192.168.2.184",
[debug] [RokuDriver@f014]     "appium:rokuEcpPort": 8060,
[debug] [RokuDriver@f014]     "appium:rokuWebPort": 80,
[debug] [RokuDriver@f014]     "appium:rokuUser": "rokudev",
[debug] [RokuDriver@f014]     "appium:rokuPass": "rokupass",
[debug] [RokuDriver@f014]     "appium:rokuHeaderHost": "192.168.2.184",
[debug] [RokuDriver@f014]     "appium:newCommandTimeout": 3600,
[debug] [RokuDriver@f014]     "appium:connectHardwareKeyboard": true
[debug] [RokuDriver@f014]   },
[debug] [RokuDriver@f014]   "firstMatch": [
[debug] [RokuDriver@f014]     {}
[debug] [RokuDriver@f014]   ]
[debug] [RokuDriver@f014] }
[RokuDriver@f014 (2dfb27d6)] Session created with session id: 2dfb27d6-ba4d-4080-8f54-a4a0e09f70d4
[Roku] Installing app from /Users/sebastian.mesa/Binaries/Redacted.zip
[Roku] Getting auth header info from 'POST http://192.168.2.184:80/plugin_install'
[Roku] Calling POST http://192.168.2.184:80/plugin_install
[debug] [AppiumDriver@22e0] Event 'newSessionStarted' logged at 1672275583922 (19:59:43 GMT-0500 (Colombia Standard Time))
[debug] [AppiumDriver@22e0] Encountered internal error running command: RequestError: Error: socket hang up
[debug] [AppiumDriver@22e0]     at new RequestError (/Users/sebastian.mesa/.appium/node_modules/@headspinio/appium-roku-driver/node_modules/request-promise-core/lib/errors.js:14:15)
[debug] [AppiumDriver@22e0]     at Request.plumbing.callback (/Users/sebastian.mesa/.appium/node_modules/@headspinio/appium-roku-driver/node_modules/request-promise-core/lib/plumbing.js:87:29)
[debug] [AppiumDriver@22e0]     at Request.RP$callback [as _callback] (/Users/sebastian.mesa/.appium/node_modules/@headspinio/appium-roku-driver/node_modules/request-promise-core/lib/plumbing.js:46:31)
[debug] [AppiumDriver@22e0]     at self.callback (/Users/sebastian.mesa/.appium/node_modules/@headspinio/appium-roku-driver/node_modules/request/request.js:185:22)
[debug] [AppiumDriver@22e0]     at Request.emit (node:events:513:28)
[debug] [AppiumDriver@22e0]     at Request.onRequestError (/Users/sebastian.mesa/.appium/node_modules/@headspinio/appium-roku-driver/node_modules/request/request.js:877:8)
[debug] [AppiumDriver@22e0]     at ClientRequest.emit (node:events:513:28)
[debug] [AppiumDriver@22e0]     at Socket.socketOnEnd (node:_http_client:512:9)
[debug] [AppiumDriver@22e0]     at Socket.emit (node:events:525:35)
[debug] [AppiumDriver@22e0]     at endReadableNT (node:internal/streams/readable:1359:12)
[debug] [AppiumDriver@22e0]     at processTicksAndRejections (node:internal/process/task_queues:82:21)
[HTTP] <-- POST /session 500 60 ms - 548
```

I'm using the following caps:
```json
{
  "platformName": "Roku",
  "appium:automationName": "roku",
  "appium:app": "/Users/sebastian.mesa/Binaries/Redacted.zip",
  "appium:rokuHost": "192.168.2.184",
  "appium:rokuEcpPort": 8060,
  "appium:rokuWebPort": 80,
  "appium:rokuUser": "rokudev",
  "appium:rokuPass": "rokupass",
  "appium:rokuHeaderHost": "192.168.2.184"
}
```

<img width="854" alt="image" src="https://user-images.githubusercontent.com/119370125/209890728-3fc704bc-e5f6-4d3b-bf15-599f2393f2a7.png">

And the Roku device is already in Dev Mode.

![IMG_2435](https://user-images.githubusercontent.com/119370125/209890644-b84462e0-dfc5-499e-96ef-a107aaddf49a.jpeg)

----------

I don't know if maybe I'm using the wrong caps, or if is a bug itself.

Appreciate any help!! 😄 
Thanks! 🚀

**Comment by jlipps** [comment]
well please try without appium inspector first of all, since the inspector doesn't support the roku driver specifically. but yeah it looks like probably a network connection issue, like maybe the appium server is on a different subnet than the roku.

**Comment by mauricio-parra-mt** [comment]
@semeguze I am facing the same issue. Did you resolve that?
