### ISSUE TITLE
Execution on local device with npm run test:e2e 

### ISSUE THREAD

**Issue by pmadival** [headspinio/appium-roku-driver#65]
Hi team,

I wanted to check the driver.
I followed following steps to test the library

1. clone the repo
2. set the env files
3. change npm run test:e2e -> point to functional tests

Started getting the following error.

Can any one help 

Thanks

```
> mocha --timeout 40s --slow 10s "./test/functional/**/*.spec.js"



  RokuDriver
WARN Appium Appium encountered 1 warning while validating drivers found in manifest /Users/pmadival/Automation/appium-roku-driver/node_modules/.cache/appium/extensions.yaml
WARN Appium Driver "roku" has 1 potential problem: 
WARN Appium   - Driver "roku" (package `@headspinio/appium-roku-driver`) has 1 invalid or missing field ("installType") in `extensions.yaml`; this may cause upgrades done via the `appium` CLI tool to fail. Please reinstall with `appium driver uninstall roku` and `appium driver install roku` to attempt a fix.
[Appium] Welcome to Appium v2.0.0-beta.46 (REV d73b7a304bde841918d0d74999c061841cbddc46)
[Appium] Non-default server args:
[Appium] {
[Appium]   address: '127.0.0.1',
[Appium]   port: 8765
[Appium] }
[Appium] Attempting to load driver roku...
[Appium] Could not load driver 'roku', so it will not be available. Error in loading the driver was: Could not find a driver installed at /Users/pmadival/Automation/appium-roku-driver/node_modules/@headspinio/appium-roku-driver
[debug] [Appium] ReferenceError: Could not find a driver installed at /Users/pmadival/Automation/appium-roku-driver/node_modules/@headspinio/appium-roku-driver
[debug] [Appium]     at DriverConfig.require (/Users/pmadival/Automation/appium-roku-driver/node_modules/appium/lib/extension/extension-config.js:527:13)
[debug] [Appium]     at map (/Users/pmadival/Automation/appium-roku-driver/node_modules/appium/lib/extension/index.js:83:46)
[debug] [Appium]     at Array.map (<anonymous>)
[debug] [Appium]     at getActiveDrivers (/Users/pmadival/Automation/appium-roku-driver/node_modules/appium/lib/extension/index.js:80:10)
[debug] [Appium]     at main (/Users/pmadival/Automation/appium-roku-driver/node_modules/appium/lib/main.js:305:25)
[debug] [Appium]     at Context.<anonymous> (/Users/pmadival/Automation/appium-roku-driver/test/functional/driver.e2e.spec.js:34:14)
[Appium] Appium REST http interface listener started on 127.0.0.1:8765
[Appium] Available drivers:
[Appium]   - roku@2.1.1 (automationName 'Roku')
[Appium] No plugins have been installed. Use the "appium plugin" command to install the one(s) you want to use.
[HTTP] --> POST /session
[HTTP] {"capabilities":{"alwaysMatch":{"default":{"appium:rokuHost":"192.168.1.120","appium:rokuEcpPort":8060,"appium:rokuWebPort":80,"appium:rokuUser":"rokudev","appium:rokuPass":"1234","appium:rokuHeaderHost":"192.168.1.120","appium:keyCooldown":1250,"appium:automationName":"Roku","appium:platformName":"Roku"}},"firstMatch":[{}]},"desiredCapabilities":{"default":{"appium:rokuHost":"192.168.1.120","appium:rokuEcpPort":8060,"appium:rokuWebPort":80,"appium:rokuUser":"rokudev","appium:rokuPass":"1234","appium:rokuHeaderHost":"192.168.1.120","appium:keyCooldown":1250,"appium:automationName":"Roku","appium:platformName":"Roku"}}}
[debug] [AppiumDriver@d68a] Calling AppiumDriver.createSession() with args: [{"default":{"appium:rokuHost":"192.168.1.120","appium:rokuEcpPort":8060,"appium:rokuWebPort":80,"appium:rokuUser":"rokudev","appium:rokuPass":"1234","appium:rokuHeaderHost":"192.168.1.120","appium:keyCooldown":1250,"appium:automationName":"Roku","appium:platformName":"Roku"}},null,{"alwaysMatch":{"default":{"appium:rokuHost":"192.168.1.120","appium:rokuEcpPort":8060,"appium:rokuWebPort":80,"appium:rokuUser":"rokudev","appium:rokuPass":"1234","appium:rokuHeaderHost":"192.168.1.120","appium:keyCooldown":1250,"appium:automationName":"Roku","appium:platformName":"Roku"}},"firstMatch":[{}]}]
[debug] [AppiumDriver@d68a] Event 'newSessionRequested' logged at 1696957994688 (22:43:14 GMT+0530 (India Standard Time))
[Appium] Could not parse W3C capabilities: All non-standard capabilities should have a vendor prefix. The following capabilities did not have one: default
[debug] [AppiumDriver@d68a] Event 'newSessionStarted' logged at 1696957994691 (22:43:14 GMT+0530 (India Standard Time))
[debug] [AppiumDriver@d68a] Encountered internal error running command: InvalidArgumentError: All non-standard capabilities should have a vendor prefix. The following capabilities did not have one: default
[debug] [AppiumDriver@d68a]     at parseCaps (/Users/pmadival/Automation/appium-roku-driver/node_modules/@appium/base-driver/lib/basedriver/capabilities.js:238:11)
[debug] [AppiumDriver@d68a]     at processCapabilities (/Users/pmadival/Automation/appium-roku-driver/node_modules/@appium/base-driver/lib/basedriver/capabilities.js:317:43)
[debug] [AppiumDriver@d68a]     at parseCapsForInnerDriver (/Users/pmadival/Automation/appium-roku-driver/node_modules/appium/lib/utils.js:134:21)
[debug] [AppiumDriver@d68a]     at AppiumDriver.createSession (/Users/pmadival/Automation/appium-roku-driver/node_modules/appium/lib/appium.js:241:26)
[debug] [AppiumDriver@d68a]     at commandExecutor (/Users/pmadival/Automation/appium-roku-driver/node_modules/@appium/base-driver/lib/basedriver/driver.js:126:9)
[debug] [AppiumDriver@d68a]     at AppiumDriver.executeCommand (/Users/pmadival/Automation/appium-roku-driver/node_modules/@appium/base-driver/lib/basedriver/driver.js:143:15)
[debug] [AppiumDriver@d68a]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[debug] [AppiumDriver@d68a]     at defaultBehavior (/Users/pmadival/Automation/appium-roku-driver/node_modules/appium/lib/appium.js:668:16)
[debug] [AppiumDriver@d68a]     at AppiumDriver.executeWrappedCommand (/Users/pmadival/Automation/appium-roku-driver/node_modules/appium/lib/appium.js:762:16)
[debug] [AppiumDriver@d68a]     at AppiumDriver.executeCommand (/Users/pmadival/Automation/appium-roku-driver/node_modules/appium/lib/appium.js:684:17)
[debug] [AppiumDriver@d68a]     at asyncHandler (/Users/pmadival/Automation/appium-roku-driver/node_modules/@appium/base-driver/lib/protocol/protocol.js:346:19)
[HTTP] <-- POST /session 400 19 ms - 1703
[HTTP] 
    1) "before all" hook in "RokuDriver"
[HTTP] Waiting until the server is closed
[HTTP] Received server close event


  0 passing (2s)
  1 failing

  1) RokuDriver
       "before all" hook in "RokuDriver":
     Error: Failed to create session.
All non-standard capabilities should have a vendor prefix. The following capabilities did not have one: default
      at startWebDriverSession (node_modules/webdriver/build/utils.js:73:15)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
      at Function.newSession (node_modules/webdriver/build/index.js:46:45)
      at remote (node_modules/webdriverio/build/index.js:77:22)
      at startSession (test/functional/driver.e2e.spec.js:21:10)
      at Context.<anonymous> (test/functional/driver.e2e.spec.js:35:14)
```

**Comment by pmadival** [comment]
Resolved after changing caps = caps.default 


Started facing this error
